name: grafana
version: 4.6.3
summary: feature rich metrics dashboard and graph editor
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Cloudwatch,
  Elasticsearch, Graphite, InfluxDB, OpenTSB, Prometheus, and Hosted Metrics.
confinement: strict
grade: stable

apps:
  grafana:
    command: 'bin/grafana.wrapper'
    plugs: [network-bind, network]
    daemon: simple

parts:
  snap-wrappers:
    plugin: dump
    source: bin
    organize:
      grafana.wrapper: bin/grafana.wrapper
  go:
    source-tag: go1.9.3
  grafana:
    after: [go]
    plugin: go
    source: https://github.com/grafana/grafana.git
    source-tag: v4.6.3
    go-importpath: github.com/grafana/grafana
    build-packages: [nodejs]
    build: |
        cd ../go/src/github.com/grafana/grafana
        go run build.go setup
        go run build.go build
    install: |
        mkdir $SNAPCRAFT_PART_INSTALL/bin $SNAPCRAFT_PART_INSTALL/conf
        cp -p $SNAPCRAFT_PART_INSTALL/../go/bin/grafana-server $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/conf/defaults.ini $SNAPCRAFT_PART_INSTALL/conf/
  grafana-ui:
    after: [grafana]
    plugin: nodejs
    source-type: git
    source: https://github.com/grafana/grafana.git
    source-tag: v4.6.3
    node-engine: '6.11.4'
    node-package-manager: yarn
    build: |
        export PATH=$HOME/.npm-global/bin:$PATH
        test -d ~/.npm-global || mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        npm install -g yarn
        yarn install --pure-lockfile
        npm run build
    install: |
        cp -rf public $SNAPCRAFT_PART_INSTALL/public
