name: grafana-ijohnson
version: 5.0.4
summary: feature rich metrics dashboard and graph editor
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Cloudwatch,
  Elasticsearch, Graphite, InfluxDB, OpenTSB, Prometheus, and Hosted Metrics.
confinement: strict
grade: stable

apps:
  grafana:
    command: 'bin/grafana.wrapper'
    plugs: [network-bind, network]
    daemon: simple

parts:
  phantomjs:
    plugin: python
    source: https://github.com/ariya/phantomjs.git
    source-type: git
    source-depth: 1
    source-tag: 2.1.3
    prepare: |
        git submodule init
        git submodule update
    build: |
        python build.py -c
    stage-packages:
        build-essential
        g++
        flex
        bison
        gperf
        ruby
        perl
        libsqlite3-dev
        libfontconfig1-dev
        libicu-dev
        libfreetype6
        libssl-dev 
        libpng-dev
        libjpeg-dev
        python
        libx11-dev
        libxext-dev
  snap-wrappers:
    plugin: dump
    source: bin
    organize:
      grafana.wrapper: bin/grafana.wrapper
  go:
    source-tag: go1.9.3
    source-depth: 1
  grafana:
    after: [go]
    plugin: go
    source: https://github.com/grafana/grafana.git
    source-tag: v5.0.4
    source-depth: 1
    go-importpath: github.com/grafana/grafana
    build: |
        cd ../go/src/github.com/grafana/grafana
        go run build.go setup
        go run build.go build
    install: |
        mkdir $SNAPCRAFT_PART_INSTALL/bin $SNAPCRAFT_PART_INSTALL/conf
        cp -p $SNAPCRAFT_PART_INSTALL/../go/bin/grafana-server $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/conf/defaults.ini $SNAPCRAFT_PART_INSTALL/conf/
  grafana-ui:
    after: [grafana]
    plugin: nodejs
    source-type: git
    source: https://github.com/grafana/grafana.git
    source-tag: v5.0.4
    node-engine: 6.11.4
    node-package-manager: yarn
    node-packages: [grunt]
    npm-run: [build]
    install: |
        cp -rf public $SNAPCRAFT_PART_INSTALL/public
