name: grafana-ijohnson
version: 6.1.2
summary: feature rich metrics dashboard and graph editor
base: core18
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Cloudwatch,
  Elasticsearch, Graphite, InfluxDB, OpenTSB, Prometheus, and Hosted Metrics.
confinement: strict
grade: stable

apps:
  grafana:
    command: 'bin/grafana.wrapper'
    plugs: [network-bind, network]
    daemon: simple

parts:
  snap-wrappers:
    plugin: dump
    source: bin
    organize:
      grafana.wrapper: bin/grafana.wrapper
  grafana:
    plugin: go
    source: https://github.com/grafana/grafana.git
    source-tag: v6.1.2
    source-depth: 1
    go-importpath: github.com/grafana/grafana
    build-packages: [build-essential, g++]
    stage-packages:
      - libfontconfig1
      - libfreetype6
    override-build: |
        cd ../go/src/github.com/grafana/grafana
        go run build.go setup
        go run build.go build
        mkdir $SNAPCRAFT_PART_INSTALL/bin $SNAPCRAFT_PART_INSTALL/conf
        cp -p $SNAPCRAFT_PART_INSTALL/../go/bin/grafana-server $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/conf/defaults.ini $SNAPCRAFT_PART_INSTALL/conf/
  grafana-ui:
    after: [grafana]
    plugin: nil
    source-type: git
    source: https://github.com/grafana/grafana.git
    source-tag: v6.1.2
    build-packages: [npm]
    override-build: |
      npm install --global yarn
      yarn remove phantomjs-prebuilt
      yarn install --pure-lockfile
      node_modules/.bin/grunt build --force
      cp -rf public $SNAPCRAFT_PART_INSTALL/public
