name: grafana-server
version: 4.6.3
grade: stable
summary: feature rich metrics dashboard and graph editor
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Graphite,
  InfluxDB & OpenTSDB.
confinement: strict
apps:
  grafana-server:
    command: 'bin/grafana-server.wrapper'
    plugs: [network-bind, network]
    daemon: simple
    stop-timeout: 1800s
parts:
  go:
    source-tag: go1.9.3
  grafana-server:
    after: [go]
    plugin: go
    source: https://github.com/grafana/grafana.git
    source-tag: v4.6.3
    go-importpath: github.com/grafana/grafana
    build-packages: [nodejs]
    build: |
        cd ../go/src/github.com/grafana/grafana
        go run build.go setup
        go run build.go build
    install: |
        mkdir $SNAPCRAFT_PART_INSTALL/bin $SNAPCRAFT_PART_INSTALL/etc
        cp -p $SNAPCRAFT_PART_INSTALL/../go/bin/grafana-server $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/conf/defaults.ini $SNAPCRAFT_PART_INSTALL/etc/

  snap-wrappers:
    plugin: dump
    source: .
    organize:
      snap_config_wrapper: bin/grafana-server.wrapper
    stage:
      - bin/grafana-server.wrapper
    prime:
      - bin/grafana-server.wrapper
