name: ammp-grafana
version: 6.2.2
summary: Grafana-based dashboarding front-end for AMMP edge devices
base: core18
description: |
  The AMMP dashboarding front-end, based on Grafana.
  NOTE: This snap is intended for a specific use case, and will not function similar to a stock version of Grafana.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf

parts:
  wrapper-scripts:
    plugin: dump
    source: bin
    organize:
      start-grafana.sh: bin/start-grafana.sh
  grafana:
    plugin: go
    source: https://snapcraft-ci:mRiJChsdg5NPwrvvgea9@gitlab.com/ammp.io/app/grafana.git
    source-branch: ammp_v6.2.2
    source-depth: 1
    go-importpath: github.com/grafana/grafana
    build-packages:
      - build-essential
      - g++
    stage-packages:
      - libfontconfig1
      - libfreetype6
    override-build: |
        cd ../go/src/github.com/grafana/grafana
        go run build.go setup
        go run build.go build
        mkdir $SNAPCRAFT_PART_INSTALL/bin $SNAPCRAFT_PART_INSTALL/conf
        cp -p $SNAPCRAFT_PART_INSTALL/../go/bin/grafana-server $SNAPCRAFT_PART_INSTALL/bin/
        cp -p $SNAPCRAFT_PART_INSTALL/../src/conf/defaults.ini $SNAPCRAFT_PART_INSTALL/conf/
  grafana-ui:
    after: 
      - grafana
    plugin: nil
    source-type: git
    source: https://snapcraft-ci:mRiJChsdg5NPwrvvgea9@gitlab.com/ammp.io/app/grafana.git
    source-branch: ammp_v6.2.2
    build-packages: 
      - npm
    override-build: |
      npm install --global yarn
      # on arm, s390x, and ppc systems remove phantomjs as required from the 
      # package.json and yarn lock as it's not available from npm on those
      # architectures
      ARCH=$(uname -m)
      case $ARCH in
      aarch64|arm*|s390*|ppc*)
        yarn remove phantomjs-prebuilt --ignore-workspace-root-check;;
      esac
      yarn install --pure-lockfile
      node_modules/.bin/grunt build --force
      cp -rf public $SNAPCRAFT_PART_INSTALL/public
  grafana-status-panel:
    plugin: dump
    source: https://github.com/ammpio/Grafana_Status_panel.git
    override-stage: |
      mv $SNAPCRAFT_PART_BUILD/dist $SNAPCRAFT_STAGE/vonage-status-panel-dist
    organize:
      vonage-status-panel-dist: plugins/vonage-status-panel/dist
  natel-discrete-panel:
    plugin: dump
    source: https://github.com/NatelEnergy/grafana-discrete-panel.git
    source-tag: v0.0.9
    override-stage: |
      mv $SNAPCRAFT_PART_BUILD/dist $SNAPCRAFT_STAGE/natel-discrete-panel-dist
    organize:
      natel-discrete-panel-dist: plugins/natel-discrete-panel/dist


apps:
  grafana:
    command: 'bin/start-grafana.sh'
    plugs: 
      - network
      - network-bind
    daemon: simple

plugs:
  provisioning-grafana:
    interface: content
    content: ammp-grafana-provisioning
    target: $SNAP/provisioning